aidotech_app:
    resource: "@AidotechAppBundle/Resources/config/routing.yml"
    prefix:   /

aidotech_core:
    resource: "@AidotechCoreBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
