aidotech_user:
    resource: "@AidotechUserBundle/Resources/config/routing.yml"
    prefix:   /user

aidotech_core:
    resource: "@AidotechCoreBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
