aidotech_core_homepage:
    path:     /
    defaults: { _controller: AidotechCoreBundle:Default:index }

aidotech_core_contact:
    path:     /contact
    defaults: { _controller: AidotechCoreBundle:Default:contact }

aidotech_core_mentions:
    path:     /mentions-legales
    defaults: { _controller: AidotechCoreBundle:Default:mentions }