<?php

namespace Aidotech\AppBundle\Repository;

/**
 * solutionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class solutionRepository extends \Doctrine\ORM\EntityRepository
{
}
