<?php

namespace Aidotech\AppBundle\Repository;

/**
 * TypeReseauRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeReseauRepository extends \Doctrine\ORM\EntityRepository
{
}
