<?php

namespace Aidotech\AppBundle\Repository;

/**
 * TypeModeleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeModeleRepository extends \Doctrine\ORM\EntityRepository
{
}
